### ISSUE TITLE
force_choice option

### ISSUE THREAD

**Issue by elvandy** [ljchang/nltools#110] opened 2017-02-28 19:40 UTC
need a more clear description for forced choice option in predict function

**Comment by ejolly** [comment] 2017-03-02 15:00
At least part of the problem is this [line](https://github.com/ljchang/nltools/blob/master/nltools/analysis.py#L93) which isn't actually doing anything

**Comment by ljchang** [comment] 2017-03-24 02:14
fixed with #119

**Closed by ljchang** 2017-03-24 02:14 UTC
